Sw 357 support dynamic groups
findologic/plugin-shopware-6 pull request #120
Opened 2020-11-04 05:30 UTC by zaifastafa

2020-11-06 10:04 UTC, TheKeymaster requested changes

2020-11-09 10:37 UTC, TheKeymaster requested changes

2020-11-09 16:34 UTC, zaifastafa commented on src/Export/DynamicProductGroupService.php
> +        return $products;
Yeah my bad. I thought I was sending the empty array that I have initialized at the top of the method.

2020-11-09 16:34 UTC, zaifastafa commented on src/Export/DynamicProductGroupService.php
> +    private function buildCriteria(): Criteria
Sarcasm? 😜

2020-11-09 16:49 UTC, TheKeymaster commented on src/Export/DynamicProductGroupService.php
> +    private function buildCriteria(): Criteria
Not at all! Really nice abstraction. Please more of that in the future!

2020-11-09 16:51 UTC, TheKeymaster commented on src/Export/DynamicProductGroupService.php
> +        return $products;
No worries, we all make mistakes! Reading the code I was like, what?!

2020-11-09 16:51 UTC, TheKeymaster commented on src/Export/DynamicProductGroupService.php
> +        if ($cacheItem->get()) {
Ah yes, it was called `isHit`.

2020-11-09 16:52 UTC, TheKeymaster approved these changes

2020-11-11 08:33 UTC, TheKeymaster approved these changes

2020-11-16 10:27 UTC, merged