Sw 504 support filter type slider
findologic/plugin-shopware-6 pull request #169
Opened 2021-03-03 07:06 UTC by zaifastafa

2021-03-04 09:48 UTC, TheKeymaster requested changes

2021-03-04 09:48 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +export default class FlFilterRangePlugin extends FilterRangePlugin {
Selecting a range and then clicking "Reset All" causes the range slider to loose its values:

![image](https://user-images.githubusercontent.com/20555112/109936611-62586700-7cce-11eb-91f7-8c133ebe00d4.png)

![image](https://user-images.githubusercontent.com/20555112/109939683-984b1a80-7cd1-11eb-9e6e-d87b6085a01b.png)

2021-03-04 09:48 UTC, TheKeymaster commented on src/Resources/app/storefront/src/scss/range-slider.scss
> +  margin: -5px 12px -2px 12px;
The margin looks kinda odd and a bit out of sync with the other margins. Applying the following styles makes this look fine again:

```suggestion
  margin: 0 12px 5px 12px;
```

2021-03-04 09:48 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +
Empty line.

2021-03-04 09:48 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +    // Binding signature
What does this comment mean?

2021-03-04 09:48 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +export default class FlFilterRangePlugin extends FilterRangePlugin {
Clicking "Reset all" should result in the range slider to reset to its default state.

Removing selected "From price..." should reset the left knob of the range slider.
Removing selected "To price..." should reset the right knob of the range slider.

2021-03-04 09:48 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +  onUpdateValues(values) {
The URL is no updated, after dragging the range-slider:

![image](https://user-images.githubusercontent.com/20555112/109942051-16102580-7cd4-11eb-80d0-06cd5e7192fe.png)

2021-03-04 09:48 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +    let start = this._inputMin.value ? this._inputMin.value : this.options.price.min;
The range slider does not seem to work on other filters except price.

![image](https://user-images.githubusercontent.com/20555112/109942378-6dae9100-7cd4-11eb-96ae-1b9b9c22b529.png)

I have created a custom field and assigned some products numerical values to it. Re-importing and configuring this filter as a range-slider, will return the proper response:

![image](https://user-images.githubusercontent.com/20555112/109942511-8f0f7d00-7cd4-11eb-9431-25973f4e9b17.png)

2021-03-04 09:48 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +    if (this._inputMin.value && this._inputMin.value < this.options.price.min) {
This check could be in a separate method.

2021-03-04 15:29 UTC, zaifastafa commented on phpunit.xml.dist
> +        <ini name="memory_limit" value="4G" />
the tests were getting memory exhaustion so I increased it so that it would work. not related to the build, but in general.

2021-03-09 11:47 UTC, TheKeymaster requested changes

2021-03-09 11:47 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +  init() {
On pages where Findologic is not active, the default Shopware 6 price filter should not be overridden. This causes the following issue:

![image](https://user-images.githubusercontent.com/20555112/110462247-b6998780-80d0-11eb-8d61-d5310afca5d7.png)

![image](https://user-images.githubusercontent.com/20555112/110462388-ec3e7080-80d0-11eb-82d5-41d9a95ee71f.png)

2021-03-09 11:47 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +  init() {
Using the slider and then clicking the Reset button to reset the filter, will properly update the input fields, but not the range knobs:

![image](https://user-images.githubusercontent.com/20555112/110465225-71775480-80d4-11eb-820a-1e3faaafe8d1.png)

2021-03-09 11:47 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +    this._inputMin.addEventListener('blur', this._onChangeMin.bind(this));
If the user presses `enter` it should also blur the input.

2021-03-09 11:47 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +   * @param id
Add a typehint.

2021-03-09 11:47 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +  onUpdateValues(values) {
Missing typehints.

2021-03-09 11:47 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +   * @param params
Add a typehint.

2021-03-09 11:47 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-range.plugin.js
> +          label: `${this.options.snippets.filterRangeActiveMinLabel} ${this._inputMin.value} ${this.options.currencySymbol}`,
Good use of the template syntax :+1:

2021-03-15 10:34 UTC, TheKeymaster requested changes

2021-03-15 10:34 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-slider-range.plugin.js
> +  _onInput(e) {
Add a typehint for `e`.

2021-03-15 10:34 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-slider-range.plugin.js
> +   * @param params
Missing typehint.

2021-03-15 10:34 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-slider-range.plugin.js
> +  setMinKnobValue(force = false) {
This argument is never set nor used in the method.

2021-03-15 10:34 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-slider-range.plugin.js
> +  setMaxKnobValue(force = false) {
This argument is never set nor used in the method.

2021-03-16 09:30 UTC, TheKeymaster requested changes

2021-03-16 09:30 UTC, TheKeymaster commented on src/Resources/app/storefront/src/js/filter-slider-range.plugin.js
> +   * @param {Object} e
The keyup event does not fire an `Object`, but a `KeyboardEvent`. See https://developer.mozilla.org/en-US/docs/Web/API/Document/keyup_event.
```suggestion
   * @param {KeyboardEvent} e
```

2021-03-17 07:57 UTC, TheKeymaster approved these changes

2021-04-06 10:26 UTC, merged