SW-639_update_readme
findologic/plugin-shopware-6 pull request #203
Opened 2021-08-11 14:12 UTC by TheKeymaster

2021-08-11 14:14 UTC, TheKeymaster commented on README.md
> -## Table of Contents
Table of contents is automatically generated by GitHub since a few months, so we no longer need to add our own.

2021-08-11 14:14 UTC, TheKeymaster commented on README.md
> +![PHPUnit configuration](docs/images/phpunit_configuration.png)
This image seems to be broken, but once merged the link is correct.

2021-08-16 07:31 UTC, dblaichinger requested changes

2021-08-16 07:31 UTC, dblaichinger commented on README.md
```suggestion
## Installation

### Production

Install the Findologic plugin from the [Shopware store](https://store.shopware.com/fin6494960032131f/findologic-suche-navigation.html).
```

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +## Development
```suggestion
### Development
```

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +### Installation
```suggestion
```

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +For an installation in production, please see [our Shopware 6 documentation](https://docs.findologic.com/doku.php?id=integration_documentation:plugin:en:integration:shopware_6).
Move this up to production section

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +These steps are only relevant for development.
This should be clear when within development section.

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +   > cd custom/plugins
Remove the `>` because it's annoying when trying to copy.

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +#### Set up
```suggestion
#### Setup
```

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +2. In the development template's root initialize the test setup (this must be run locally, outside the app container)
```suggestion
2. In the development templates, root initialize the test setup (Run locally, outside the app container)
```

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +- For a development build, use `./psh.phar storefront:dev`
```suggestion
- For development build: `./psh.phar storefront:dev`
```

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +- For a production build, use `./psh.phar storefront:build`
```suggestion
- For production build: `./psh.phar storefront:build`
```

2021-08-16 07:31 UTC, dblaichinger commented on README.md
> +JavaScript files.
Maybe also use list points here?

2021-08-16 12:22 UTC, dblaichinger approved these changes

2021-08-16 13:30 UTC, merged