Showlanguage that has url associated with it
findologic/plugin-shopware-6 pull request #238
Opened 2022-01-03 09:11 UTC by D3xter7

2022-01-07 06:14 UTC, zaifastafa commented
The build will pass once #239 is merged.

2022-01-10 09:39 UTC, TheKeymaster requested changes

2022-01-10 09:39 UTC, TheKeymaster commented on src/Resources/app/administration/src/module/findologic-module/page/findologic-page/index.js
> +                    let domain = selectedChannel.domains.find(item => item.languageId === language.id);
Always prefer `const` over `let`

```suggestion
                    const domain = selectedChannel.domains.find(item => item.languageId === language.id);
```

2022-01-10 09:39 UTC, TheKeymaster commented on src/Resources/app/administration/src/module/findologic-module/page/findologic-page/index.js
> +                        if(domain.url !== null && domain.url !== ""){
Always use single quotes instead of double quotes.

```suggestion
                        if(domain.url !== null && domain.url !== ''){
```

2022-01-10 09:39 UTC, TheKeymaster commented on src/Resources/app/administration/src/module/findologic-module/page/findologic-page/index.js
> +                        if(domain.url !== null && domain.url !== ""){
Please make sure to use proper code style

```suggestion
                    if (domain) {
                        if (domain.url !== null && domain.url !== "") {
```

2022-01-14 15:56 UTC, zaifastafa commented on src/Resources/app/administration/src/module/findologic-module/page/findologic-page/index.js
> +                        if(domain.url !== null && domain.url !== ''){
This was not fixed.

2022-01-17 09:51 UTC, TheKeymaster approved these changes

2022-01-17 10:03 UTC, merged