Sw 619 adding adapters
findologic/plugin-shopware-6 pull request #264
Opened 2022-03-21 14:56 UTC by msilinskas

2022-04-06 08:16 UTC, TheKeymaster requested changes

2022-04-06 08:16 UTC, TheKeymaster commented on src/Export/Adapters/DateAddedAdapter.php
> +        if (null === $releaseDate) {
Please don't use yoda conditions :D

2022-04-06 08:16 UTC, TheKeymaster commented on src/Export/Adapters/NameAdapter.php
> +        if (!$name) {
Why was this added? If the product has no name an exception should be thrown.

2022-04-06 08:16 UTC, TheKeymaster commented on src/Export/Adapters/OrderNumberAdapter.php
> +    private function getChildrenProductsOrderNumbers(ProductEntity $product): array
The adapters shouldn't fetch data from children products. Instead (this will be done in a future story) each child should call the `adapt` method to get the required data. For now please make sure no adapter gets any data from children.

2022-04-06 08:16 UTC, TheKeymaster commented on src/Export/Adapters/OrderNumberAdapter.php
> +            if (null === $orderNumber) {
![7182_yoda](https://user-images.githubusercontent.com/20555112/161926092-31c32b33-a6e7-4280-b90d-8024b3bc6493.png): Remove you should these yoda expressions. 

Please just check through your code, there may be other occurrences.

2022-04-06 08:16 UTC, TheKeymaster commented on src/Export/Adapters/PropertiesAdapter.php
> +    private $properties = [];
Adapters should not be state aware and this is dangerous. If you would call this adapter multiple times, you will pollute it more and more, which not only only gives you incorrect data, but may eventually also cause a memory-leak. Please don't store any data in a service.

2022-04-06 08:16 UTC, TheKeymaster commented on src/Export/Adapters/SalesFrequencyAdapter.php
> +        if (!$orders->getTotal()) {
This would also fail if it was `0` and `getTotal` always returns an `int` anyway, so what's the point of this check?

2022-04-06 08:16 UTC, TheKeymaster commented on src/Export/Adapters/SalesFrequencyAdapter.php
> +    public function adapt(ProductEntity $product): ?SalesFrequency
salesfrequency shouldn't be nullable. Either it hasn't sold, which would be `0`, or it has been sold, which would be the count of products sold.

2022-04-06 08:16 UTC, TheKeymaster commented on src/Export/Adapters/SalesFrequencyAdapter.php
> +    private function getCriteria(ProductEntity $product): Criteria
Maybe `buildCriteria` would suit better here.

2022-04-13 14:58 UTC, TobiasGraml11 requested changes

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/AdapterFactory.php
> +
I think it would make sense to set this and the adapters above `private` as well

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/AttributeAdapter.php
> +use Psr\Container\ContainerInterface;
This import is unused

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/DateAddedAdapter.php
> +        }
This should also work:
```suggestion
        if (!$releaseDate = $product->getReleaseDate()) {
            return null;
        }
```

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/DescriptionAdapter.php
> +        return $value;
I think we should stay consistent here, you are creating the `Description` class just before setting the value in the `DateAddedAdapter`.
```suggestion
        if (!$descriptionValue = $this->getDescription($product)) {
            return null;
        }

        $description = new Description();
        $description->setValue($descriptionValue);

        return $description;
```

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/ImagesAdapter.php
> +    private $productImageService;
This member variables are set to `protected` in the `AttributeAdapter`. I think it makes sense to make it `protected`, so that the service can be used in plugin extensions.

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/KeywordsAdapter.php
> +use Shopware\Core\System\Tag\TagCollection;
Unused import

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/KeywordsAdapter.php
> +    }
Please make those functions `protected`, so they can be used and overwritten in extension plugins.
This also relates to other adapters.

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/OrderNumberAdapter.php
> +}
We will need to export all 3 types of order numbers. Currently, only the product number would be exported.

```suggestion
    private function getOrderNumber(ProductEntity $product): ?Ordernumber
    {
        $ordernumbers = [];
    
        if (!Utils::isEmpty($product->getProductNumber())) {
            $ordernumbers[] = new Ordernumber($product->getProductNumber());
        }

        if (!Utils::isEmpty($product->getEan())) {
            $ordernumbers[] = new Ordernumber($product->getEan());
        }

        if (!Utils::isEmpty($product->getManufacturerNumber())) {
            $ordernumbers[] = new Ordernumber($product->getManufacturerNumber());
        }

        return $ordernumbers;
    }
}
```

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/OrderNumberAdapter.php
> +        return $this->getParentItemOrderNumber($product);
I think this function only needs to include the suggested content of `getOrderNumber` from my comment below (or above?). Splitting this into 2 extra functions seems kinda unnecessary.

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/ImagesAdapter.php
> +    private $productImageService;
Please also consider this for the other adapters

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/SalesFrequencyAdapter.php
> +    public function adapt(ProductEntity $product): SalesFrequency
> All `adapt()` methods that only return a single instance such as Name, must also be nullable (this way an extension could optionally simply return null)
```suggestion
    public function adapt(ProductEntity $product): ?SalesFrequency
```

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/Adapters/UserGroupsAdapter.php
> +    public function adapt(ProductEntity $product, ExportContext $exportContext): array
Please include the export context via constructor parameter, like it is done in the `AttributeAdapter`.

2022-04-13 14:58 UTC, TobiasGraml11 commented on src/Export/ExportItemAdapter.php
> +        $item->setSalesFrequency($this->adapterFactory->getSalesFrequencyAdapter()->adapt($product));
We should also move this inside a nullable check, as the return type should be nullable

2022-04-13 14:58 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +use Shopware\Core\System\SalesChannel\SalesChannelEntity;
A lot of unused imports

2022-04-13 14:58 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +use FINDOLOGIC\FinSearch\Exceptions\Export\Product\ProductHasNoCategoriesException;
As this exception is an unused import, it suggests that you forgot about the test for it.
This exception was tested in `testProductAndVariantHaveNoCategories`

2022-04-13 14:58 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +     * @param array<string, string> $customFields
This type does not fit for multidimensional custom fields
```suggestion
     * @param array<string, string|array> $customFields
```

2022-04-13 14:58 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +        $data['customFields'] = ['long_value' => str_repeat('und wieder, ', 20000)];
`$customFields` is never used, did you mean?:
```suggestion
    public function testProductWithMultiSelectCustomFields(
        array $customFields,
        array $expectedCustomFieldAttributes
    ): void {
        $data['customFields'] = $customFields;
```

2022-04-13 14:58 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +class AttributeAdapterTest extends TestCase
Some tests that seem to be skipped, or at least I can't find them.:
- testProductAndVariantHaveNoCategories
- testOnlyUniqueCategoriesAreExported

Correct me, if I am wrong.

2022-04-13 14:58 UTC, TobiasGraml11 commented on tests/Export/Adapters/DescriptionAdapterTest.php
> +use Shopware\Core\System\SalesChannel\SalesChannelContext;
Unused imports. Please also check the other adapter test classes.

2022-04-13 14:58 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +namespace FINDOLOGIC\FinSearch\Tests\Export;
This needs to be changed in all adapter test files

```suggestion
namespace FINDOLOGIC\FinSearch\Tests\Export\Adapters;
```

2022-04-13 14:58 UTC, TobiasGraml11 commented on tests/Export/Adapters/PropertiesAdapterTest.php
> +class PropertiesAdapterTest extends TestCase
I think your are missing following test:
- testNonFilterablePropertiesAreExportedAsPropertiesInsteadOfAttributes

2022-04-13 14:58 UTC, TobiasGraml11 commented on tests/Traits/DataHelpers/ProductHelper.php
> +    }
How about moving this into an `ImageHelper`?

2022-04-20 15:12 UTC, TobiasGraml11 requested changes

2022-04-20 15:12 UTC, TobiasGraml11 commented on src/Export/Adapters/DescriptionAdapter.php
> +    private function getDescription(ProductEntity $product): ?string
Please make it `protected`

2022-04-20 15:12 UTC, TobiasGraml11 commented on src/Export/Adapters/PropertiesAdapter.php
> +    private $config;
Please make them `protected`

2022-04-20 15:12 UTC, TobiasGraml11 commented on src/Export/Adapters/SalesFrequencyAdapter.php
> +    private $salesChannelContext;
Please make them `protected`

2022-04-20 15:12 UTC, TobiasGraml11 commented on src/Export/Adapters/UserGroupsAdapter.php
> +    private $exportContext;
Please make it `protected`

2022-04-20 15:12 UTC, TobiasGraml11 commented on src/Export/Adapters/OrderNumberAdapter.php
> +}
```suggestion
class OrderNumberAdapter
{
    public function adapt(ProductEntity $product): array
    {
        return $this->getOrderNumbers($product);
    }

    protected function getOrderNumbers(ProductEntity $product): array
    {
        $orderNumbers = [];

        if (!Utils::isEmpty($product->getProductNumber())) {
            $orderNumbers[] = new Ordernumber($product->getProductNumber());
        }

        if (!Utils::isEmpty($product->getEan())) {
            $orderNumbers[] = new Ordernumber($product->getEan());
        }

        if (!Utils::isEmpty($product->getManufacturerNumber())) {
            $orderNumbers[] = new Ordernumber($product->getManufacturerNumber());
        }

        return $orderNumbers;
    }
}
```

2022-04-20 15:12 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +namespace FINDOLOGIC\FinSearch\Tests\Adapters\Export;
This should always correspond to the path.

This is the case for all adapter tests.
```suggestion
namespace FINDOLOGIC\FinSearch\Tests\Export\Adapters;
```

2022-04-21 13:24 UTC, TobiasGraml11 approved these changes

2022-04-25 15:01 UTC, dblaichinger commented on src/Export/Adapters/NameAdapter.php
> +    protected function getCleanedName(ProductEntity $product): ?string
In which case can the return value be `null`? The product name is required for the exported data so it would be better to run into ProductHasNoNameException instead

2022-04-25 15:01 UTC, dblaichinger commented on src/Export/Adapters/UrlAdapter.php
> +        if (!$rawUrl) {
Is this also a valid case? 
`urlBuilderService->buildProductUrl()` also declares non-nullable string as return.

2022-04-25 15:01 UTC, dblaichinger commented on src/Export/ExportItemAdapter.php
> +        }
Names and urls have been always set before, why do we need the if checks here?

2022-04-25 15:11 UTC, msilinskas commented on src/Export/Adapters/NameAdapter.php
> +    protected function getCleanedName(ProductEntity $product): ?string
Yep, it's not necessary here.

2022-04-25 15:17 UTC, TobiasGraml11 commented on src/Export/Adapters/NameAdapter.php
> +    protected function getCleanedName(ProductEntity $product): ?string
@dblaichinger @msilinskas  This is related to this point in the story:
> All adapt() methods that only return a single instance such as Name, must also be nullable (this way an extension could optionally simply return null)

2022-04-25 15:18 UTC, TobiasGraml11 commented on src/Export/ExportItemAdapter.php
> +        }
@dblaichinger @msilinskas This is related to this point in the story:

> All adapt() methods that only return a single instance such as Name, must also be nullable (this way an extension could optionally simply return null)

2022-04-25 15:19 UTC, msilinskas commented on src/Export/Adapters/NameAdapter.php
> +    protected function getCleanedName(ProductEntity $product): ?string
@TobiasGraml11 I guess that only adapt method should be nullable as it is now?

2022-04-25 15:21 UTC, TobiasGraml11 commented on src/Export/Adapters/NameAdapter.php
> +    protected function getCleanedName(ProductEntity $product): ?string
@msilinskas Yes, "child" functions can be whatever they are, as you don't have to extend them.

2022-04-25 17:03 UTC, dblaichinger commented on src/Export/Adapters/NameAdapter.php
> +    protected function getCleanedName(ProductEntity $product): ?string
@TobiasGraml11 Makes sense, we should make the adapt methods nullable. Let's discuss if we should add an exception for required values and let the product skip in SW-666 then.

2022-04-26 08:23 UTC, merged