Sw 704 export variant specific data
findologic/plugin-shopware-6 pull request #281
Opened 2022-05-05 12:54 UTC by msilinskas

2022-05-05 14:08 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +        );
I would suggest something like:

```suggestion
        $criteria = $this->getBaseCriteria($limit, $offset);
        $this->adaptCriteriaBasedOnConfiguration($criteria)
```

2022-05-05 14:08 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +        $criteria = new Criteria();
```suggestion
    protected function getBaseCriteria(?int $limit = null, ?int $offset = null): Criteria
    {
        $criteria = $this->getCriteriaWithProductVisibility();
```

2022-05-05 14:08 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +    }
```suggestion
    protected function adaptCriteriaForMainProductConfiguration(Criteria $criteria): Criteria
    {
        $criteria->addFilter(
            new EqualsFilter('parentId', null)
        );
    }
```

2022-05-05 14:08 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +    }
You will probably need to check the price of the main product and the cheapest variant after the database call. Except you can think about a way of requesting it directly from the database:

Something like this:
```php
protected function getCheapestVariant(ProductEntity $product): ProductEntity
{
    $currencyId = $this->salesChannelContext->getSalesChannel()->getCurrencyId();
    $cheapestVariant = $product->getChildren()->first();

    $productPrice = $product->getCurrencyPrice(currencyId);
    $cheapestVariantPrice = $cheapestVariant->getCurrencyPrice(currencyId);

    return $productPrice->getGross() < $cheapestVariantPrice->getGross() ? $product : $cheapestVariant;
}
```

```suggestion
    protected function adaptCriteriaForCheapestVariantConfiguration(Criteria $criteria): void
    {
        $children = $criteria->getAssociation('children');
        $children->setLimit(1);
        $children->addSorting(
            new FieldSorting('price', FieldSorting::ASCENDING)
        );
        $this->handleAvailableStock($children);
        $this->addVisibilityFilter($children);
        $this->addPriceZeroFilter($children);
    }
```

Maybe you can even filter out variants, that are more expensive than the main product. This way, you could simplify the check I mentioned above

2022-05-05 14:08 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +    }
```suggestion
    protected function adaptCriteriaBasedOnConfiguration(Criteria $criteria): Criteria
    {
        $mainVariantConfig = $this->config->getMainVariant();

        switch ($mainVariantConfig) {
            case MainVariant::SHOPWARE_DEFAULT:
                break;
            case MainVariant::MAIN_PARENT:
                $this->adaptCriteriaForMainProductConfiguration($criteria);
                break;
            case MainVariant::CHEAPEST:
                $this->adaptCriteriaForCheapestVariantConfiguration($criteria);
                break;
            default:
                throw new InvalidArgumentException($mainVariantConfig);
        }
    }
```

2022-05-05 14:08 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +    public function searchVisibleProducts(
This function should return exactly what the function did in `ProductService` (without requesting all the variants). Just the logic behind it should be made much better and clearer.
And what the function did, was returning a list of products according to the plugin configuration:
- default: return the products how SW does it in their code
- main/parent product: Get the main product or the main variant (Can be configured in the product configuration)
- cheapest: Get the cheapest variant. Use the main product, if there is no cheapest

2022-05-30 10:28 UTC, TobiasGraml11 requested changes

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Controller/ExportController.php
> +//        );
This can be removed now

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Controller/ExportController.php
> +//        dd($products);
This can be removed now

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Controller/ExportController.php
> +        $this->productService = ProductServiceSeparateVariants::getInstance(
Please also update it for the member variable docblock

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Controller/ExportController.php
>  use FINDOLOGIC\FinSearch\Export\ProductService;
Should not be needed anymore

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Controller/ExportController.php
>  use FINDOLOGIC\FinSearch\Export\HeaderHandler;
It seems like the `$salesChannelContextFactory` member variable is not needed at all for this controller.
Could you please remove that? As this will be a major release, I think we can do that.

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ExportItemAdapter.php
> +    /** @var LoggerInterface  $logger*/
For consistency, please also add it to the other member variables

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ExportItemAdapter.php
> +        }
I think it makes sense to also log exceptions for variants

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ExportItemAdapter.php
> +    public function adaptVariant(Item $item, ProductEntity $product): void
We should also return the `Item` here

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductImageService.php
>          }
I guess this could make issues with the existing export logic. Does any test fail?
Maybe we need some `$considerVariants = true` parameter, which we set to `false` in our adapters.

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/XmlExport.php
> +        }
Why is this needed?
Is this, to export variant information, even when the main product throws an exception?

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/XmlExport.php
> +        $item = $exportItemAdapter->adapt($initialItem, $productEntity);
This whole block seems very intuitive, I have some ideas:
- Create member variable for `$exportItemAdapter` and `$productService` in this class and `$exportItemAdapter` in `ExportController`
- Forward both in `Export::getInstance`
- Move the `getMaxPropertiesCount` call inside of `calculatePageSize`
- Get the page size just one line above `buildVariantIterator`

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Utils/Utils.php
> +                //                'children.properties.productConfiguratorSettings.option.group.translations',
We will still need those associations for the old logic.
I would suggest to create `addChildrenAssociation`, and additionally call this in `ProductService::addProductAssociations`

2022-05-30 10:28 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +use FINDOLOGIC\Export\Data\Ordernumber;
Unused

2022-05-30 10:28 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
>          $adapter = $this->getContainer()->get(AttributeAdapter::class);
Should we set this as member variable in `setUp`?

2022-05-30 10:28 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
>          $adapter = $this->getContainer()->get(AttributeAdapter::class);
We can use that, when an adapter without custom config can be used

2022-05-30 10:28 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +        $item = $exportItemAdapter->adapt($initialItem, $productEntity);
Can't we just use the `AttributeAdapter` here?

2022-05-30 10:28 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +        $item = $exportItemAdapter->adapt($initialItem, $productEntity);
This would also simplify the assertion without `ReflectionClass`

2022-05-30 10:28 UTC, TobiasGraml11 commented on tests/Export/Adapters/OrderNumbersAdapterTest.php
> +            'parentId' => $id,
You could remove this variable and use `$product->getId()`

2022-05-30 10:28 UTC, TobiasGraml11 commented on tests/Export/Adapters/OrderNumbersAdapterTest.php
> +           'id' => $variantId,
`$variantId` is not used otherwise, so you can just use `Uuid::randomHex()` directly.

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +use Shopware\Core\Framework\DataAbstractionLayer\Search\Filter\AndFilter;
Unused

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +        return $result;
```suggestion
        return $this->getVisibleProducts($limit, $offset, $productId);
```

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +    }
I can't find any usage of this function

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +class ProductServiceSeparateVariants
I always had a hard time finding the correct place of functions, while working on it.
Could you sort them a bit by the call timing? As an example, `getVisibleProducts` is basically one of the entry point functions, but is placed very far down.
Also: `public` functions should usually be placed on top and all the others afterwards

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +        $productRepository = $this->container->get('product.repository');
The product repository is used 7 times in the class, we should fetch this once in the constructor.

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +    protected function getFirstChildren(ProductEntity $product): ?ProductEntity
`getFirstChild` seems to be correct, according to the functionality

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +        return $mainVariants;
```suggestion
        $mainVariants = $this->getConfiguredMainVariants($products->getEntities());
        
        return $mainVariants ?: $products;
```

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +        return $mainVariants;
Wouldn't this wrongly export the main variant for "Shopware default", or is this how it should be anyway?

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +                    ? $product : $cheapestVariant;
```suggestion
                $realCheapestProduct = $productPrice->getGross() <= $cheapestVariantPrice->getGross()
                    ? $product
                    : $cheapestVariant;
```

2022-05-30 10:28 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +        $inactiveParentWithChildsFilter = new MultiFilter(
```suggestion
        $inactiveParentWithChildrenFilter = new MultiFilter(
```

2022-06-02 10:53 UTC, msilinskas commented on src/Export/XmlExport.php
> +        }
Yes, it's for exporting a variants information, even if the main variant throws an error

2022-06-02 11:12 UTC, msilinskas commented on src/Export/ProductServiceSeparateVariants.php
> +    }
It's used in the ProductServiceSeparateVariantsTest::testFindsAllProducts

2022-06-02 11:29 UTC, msilinskas commented on tests/Export/Adapters/AttributeAdapterTest.php
> +        $item = $exportItemAdapter->adapt($initialItem, $productEntity);
Calling the attribute adapter here directly we can't make sure, that only unique categories was exported

2022-06-02 12:31 UTC, msilinskas commented on src/Export/ProductServiceSeparateVariants.php
> +        return $mainVariants;
In the old behavior we also used a main variants if it was able to.

2022-06-02 12:46 UTC, TobiasGraml11 commented on src/Export/ProductServiceSeparateVariants.php
> +    }
Yeah, but why would we need to have a function, just to test it?
So if the function is not needed, the test is also irrelevant.

2022-06-02 12:56 UTC, TobiasGraml11 commented on tests/Export/Adapters/AttributeAdapterTest.php
> +        $item = $exportItemAdapter->adapt($initialItem, $productEntity);
Ah, I see!

2022-06-08 14:43 UTC, TobiasGraml11 requested changes

2022-06-08 14:43 UTC, TobiasGraml11 commented on src/Export/Adapters/AdapterFactory.php
> +        $this->shopwarePropertiesAdapter = $shopwarePropertiesAdapter;
Please keep the alphabetic order

2022-06-08 14:43 UTC, TobiasGraml11 commented on src/Export/Adapters/AdapterFactory.php
> +    }
Please keep the alphabetic order

2022-06-08 14:43 UTC, TobiasGraml11 commented on src/Export/Adapters/PropertiesAdapter.php
> +class PropertiesAdapter extends ShopwarePropertiesAdapter
Please also split the adapter tests and move the tests to the correct test file

2022-06-08 14:43 UTC, TobiasGraml11 commented on src/Export/Adapters/PropertiesAdapter.php
> +class PropertiesAdapter extends ShopwarePropertiesAdapter
Please make them independent from each other, so call each one separately.

2022-06-08 14:43 UTC, TobiasGraml11 commented on src/Export/Adapters/PropertiesAdapter.php
> +class PropertiesAdapter extends ShopwarePropertiesAdapter
To make it more clear, I would call `PropertiesAdapter` something like `DefaultPropertiesAdapter`

2022-06-08 14:43 UTC, TobiasGraml11 commented on src/Resources/config/services/services.xml
> +            <argument type="service" id="FINDOLOGIC\FinSearch\Export\Adapters\ShopwarePropertiesAdapter" />
Please keep the alphabetic order

2022-06-08 14:43 UTC, TobiasGraml11 commented on src/Resources/config/services/services.xml
> +
Please keep the alphabetic order

2022-06-13 05:02 UTC, TobiasGraml11 approved these changes

2022-06-13 08:52 UTC, merged