SW-805 Wrong prices are exported
findologic/plugin-shopware-6 pull request #399
Opened 2024-04-24 11:44 UTC by Radomir98

2024-04-26 11:04 UTC, TobiasGraml11 requested changes

2024-04-26 11:04 UTC, TobiasGraml11 commented on src/Resources/app/administration/src/module/findologic-module/snippet/en-GB.json
> +                    "helpText": "This domain is used for multi-domain sales channels, and the selected domain will be used as uri for product url"
Please adapt these, so they represent the real usage. For now, we basically only use the configured currency. I'll translate them to German afterwards.

2024-04-26 11:04 UTC, TobiasGraml11 commented on src/Findologic/Config/FindologicConfigService.php
> +    public function getDomainId($channelId = null, $languageId = null): ?string
As you can see by the existing function, this service is not really the place to fetch specific config values. They are only fetched by the config key.

2024-04-26 11:04 UTC, TobiasGraml11 commented on src/Export/Services/SalesChannelService.php
> +        $currencyId = $this->findologicConfigService->getDomainCurrencyId($currentContext);
Relying on the current context could lead to issues, when the shopkey is requested on a different sales channel.
We should fetch the domain within the if block below according to the `languageId` and `salesChannelId`. If no `domainId` is configured, I guess we just take the first one.

2024-08-01 11:55 UTC, Bibarella approved these changes
LGTM

2024-09-30 09:42 UTC, merged